Import('*')

env.Prepend(LIBS = [
    intelwinsys,
    trace,
    rbug,
    mesautil,
    mesa,
    glsl,
    gallium
])

if True:
    env.Append(CPPDEFINES = [
        'GALLIUM_SOFTPIPE',
        'GALLIUM_RBUG',
        'GALLIUM_TRACE',
    ])
    env.Prepend(LIBS = [softpipe])

env.Prepend(LIBS = [libgl])

env.Append(CPPPATH = [
    '#/src/mapi',
    '#/src/mesa',
    '#/src/mesa/main',
    '#/include/HaikuGL',
	'#/src/gallium/winsys',
    '#/src/gallium/drivers/ilo',
    '#/src/gallium/winsys/intel/hgl',
    '/boot/system/develop/headers/private',
])

if env['llvm']:
    env.Append(CPPDEFINES = ['GALLIUM_LLVMPIPE'])
    env.Prepend(LIBS = [llvmpipe])

intel_sources = [
    'GalliumContext.cpp',
    'GalliumFramebuffer.cpp',
    'IntelRenderer.cpp'
]

# libhwintel gets turned into "Intel" by the haiku package system
module = env.LoadableModule(
    target ='hwintel',
    source = intel_sources,
)

