#######################################################################
# SConscript for haiku winsys


Import('*')

if env['platform'] in ('haiku'):

    env = env.Clone()

    env.Append(CPPPATH = [
        '#/src/gallium/include',
        '#/src/gallium/auxiliary',
        '#/src/gallium/drivers',
    ])

    intelwinsys = env.ConvenienceLibrary(
        target = 'intelwinsys',
        source = [
           'intel_hgl_winsys.c',
        ]
    )
    Export('intelwinsys')
